listener {
    timeout = 600                                                  # 10 min
    on-timeout = hyprctl dispatch dpms off eDP-1                   # turn off built-in monitor
    on-resume = hyprctl dispatch dpms on eDP-1                     # turn it back on
}
